In [1]:
import numpy as np
from module2.week2 import matrix_multi_matrix, matrix_multi_vector, inverse_matrix, compute_eigenvalues_eigenvectors,compute_cosine

vector_a=>[0 1 2 3 4]
vector_b=>[10 11 12 13 14]
matrix_a=>[[0 1 2 3 4]
 [5 6 7 8 9]]
matrix_b=>[[10 11 12 13 14]
 [15 16 17 18 19]]
matrix_c=>[[0 2]
 [4 6]]
a) Đội dài của vector
vector_a=>[0 1 2 3 4]
compute_vector_length=>5.477225575051661
23.28
b) Phép tích vô hướng
vector_a=>[0 1 2 3 4]
vector_b=>[10 11 12 13 14]
compute_dot_product=>130
4
c) Nhân vector với ma trận:
vector_a=>[0 1 2 3 4]
matrix_a=>[[0 1 2 3 4]
 [5 6 7 8 9]]
matrix_multi_vector=>[30 80]
d) Nhân ma trạn với  ma trận:
matrix_a=>[[0 1 2 3 4]
 [5 6 7 8 9]]
vector_a=>[[10 11 12 13 14]
 [15 16 17 18 19]]
matrix_multi_matrix=>[[  0  11  24  39  56]
 [ 75  96 119 144 171]]
e) Ma trận nghịch đảo:
matrix_c=>[[0 2]
 [4 6]]
inverse_matrix=>[[-0.75  0.25]
 [ 0.5   0.  ]]
vector=>[[0.9 0.2]
 [0.1 0.8]]
compute_eigenvalues_eigenvectors=>EigResult(eigenvalues=array([1. , 0.7]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))
vector_a=>[0 1 2 3 4]
vector_b=>[10 11 12 13 14]
matrix_a=>[[0 1 2 3 

In [29]:



x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result', x @ k)

result [ 3 -5]


In [30]:


m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
print(m @ v)

[3 1]


In [16]:


m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = m1 @ m2
print(result)

[[  6  -1]
 [-16 -10]]


In [17]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1 @ m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [19]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[5. 5. 5. 5.]


In [20]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[29 29 29 29]


In [23]:

m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [26]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [2]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577
