Cosine Similarity (Độ tương đồng cosine ) là một thước đo dùng để xác định độ tương đồng giữa hai vector trong không gian
vector trong không gian vector.

Định nghĩa:
Cosine similarity giữa hai vector A và B được định nghĩa như sau:

Cosine Similarity(A,B)= tích vô hướng / tích độ dài 

In [1]:
import numpy as np


def compute_cosine(A, B):
	dot_prod = np.dot(A, B)
	normA = np.linalg.norm(A)
	normB = np.linalg.norm(B)

	cos_sim = dot_prod / (normA * normB)
	return cos_sim


In [2]:
vector_3d_A = np.arange(1, 10).reshape(3, 3)
vector_3d_B = np.arange(11, 20).reshape(3, 3)

vector_1d_A = np.arange(1, 5)
vector_1d_B = np.array([1, 0, 3, 0])

print(f"vector_3d_A: {vector_3d_A}")
print(f"vector_3d_B: {vector_3d_B}")
print(f"cosine similarity: {compute_cosine(vector_3d_A, vector_3d_B)}")

print(f"vector_1d_A: {vector_1d_A}")
print(f"vector_1d_B: {vector_1d_B}")
print(f"cosine similarity: {compute_cosine(vector_1d_A, vector_1d_B)}")


vector_3d_A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
vector_3d_B: [[11 12 13]
 [14 15 16]
 [17 18 19]]
cosine similarity: [[0.11675273 0.12453625 0.13231976]
 [0.28020656 0.29966534 0.31912413]
 [0.44366038 0.47479444 0.5059285 ]]
vector_1d_A: [1 2 3 4]
vector_1d_B: [1 0 3 0]
cosine similarity: 0.5773502691896257
