In [1]:
import torch
import torch.nn as nn
import math

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim = 0)
output = softmax_function(data)
assert math.isclose(round(output[0].item(), 2), 0.09)
output

tensor([0.0900, 0.2447, 0.6652])

In [4]:
import torch
import torch.nn as nn


class MySoftmax(nn.Module):

	def __init__(self):
		super().__init__()

	def forward(self, x):
		### Your Code Here
		# Kiểm tra xem đầu vào có phải là tensor 1 chiều hay không
		if x.dim() != 1:
			raise ValueError("Đầu vào phải là một tensor 1 chiều")

		# Tính lũy thừa của từng phần tử trong tensor
		exp_x = torch.exp(x)

		# Chia từng phần tử lũy thừa cho tổng các giá trị lũy thừa để tính softmax
		return exp_x / torch.sum(exp_x)


### End Code Here


data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert math.isclose(round(output[-1].item(), 2), 0.26)
output

tensor([0.7054, 0.0351, 0.2595])

In [5]:
data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert math.isclose(round(output[0].item(), 2), 0.0)
output

tensor([0., 0., nan])

In [6]:
class SoftmaxStable(nn.Module):
	def __init__(self):
		super(SoftmaxStable, self).__init__()

	def forward(self, x):
		# Kiểm tra xem đầu vào có phải là tensor 1 chiều hay không
		if x.dim() != 1:
			raise ValueError("Đầu vào phải là một tensor 1 chiều")

		# Lấy giá trị lớn nhất trong tensor để trừ đi từng phần tử, giúp tăng độ ổn định tính toán
		max_x = torch.max(x)

		# Tính lũy thừa của từng phần tử sau khi trừ đi giá trị lớn nhất
		exp_x = torch.exp(x - max_x)

		# Chia từng phần tử lũy thừa cho tổng các giá trị lũy thừa để tính softmax
		return exp_x / torch.sum(exp_x)


data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67

tensor([0.0900, 0.2447, 0.6652])