Bài tập 1 (kỹ thuật đọc và xử lý dữ liệu từ file .csv): Cho trước file dữ liệu advertising.csv, hãy hoàn
thành function load_data_from_file() trả về dữ liệu đã được tổ chức (features_X cho input và
sales_Y cho output).

In [44]:
import random

import numpy as np

random.seed(0)  # please do not remove this line
%matplotlib inline

def load_data_from_file(fileName = "../../../data/module4/week3/advertising.csv"):
	data = np.genfromtxt(fileName, dtype = None, delimiter = ',', skip_header = 1)
	features_X = data[:, :3]
	sales_Y = data[:, 3]
	# ****** your code here ******************
	new_features_X = np.zeros((features_X.shape[0], 4))
	for i in range(len(features_X)):
		new_features_X[i] = np.concatenate(([new_features_X[i][0]], features_X[i]))

	return new_features_X, sales_Y


Question 2: Hãy cho biết kết quả của đoạn chương trình sau:

In [43]:
features_X, _ = load_data_from_file()
print(features_X[:5, :])

[[  0.  230.1  37.8  69.2]
 [  0.   44.5  39.3  45.1]
 [  0.   17.2  45.9  69.3]
 [  0.  151.5  41.3  58.5]
 [  0.  180.8  10.8  58.4]]


Question 3: Hãy cho biết kết quả của đoạn chương trình sau:

In [45]:
_, sales_Y = load_data_from_file()
print(sales_Y.shape)

(200,)


Bài tập 2 (kỹ thuật khởi tạo giá trị cho từng gene trong chromosome (individual), tạo ra các

giá trị ngẫu nhiên cho một cá thể (tham số theta của mô hình)): hãy hoàn thiện function cre-
ate_individual(n,bound) để khởi tạo ngẫu nhiên giá trị của n genes (tham số θi) trong chromosome

với giá trị từng gene được khởi tạo [-bound/2, bound/2]

In [53]:
def create_individual(n = 4, bound = 10):
	# *************** Your code here *******
	individual = [random.uniform(-bound / 2, bound / 2) for _ in range(n)]
	return individual


individual = create_individual()
print(individual)

[4.130110532378982, 4.666063677707587, -0.22990223447282965, 3.6530992777164]


Bài tập 3 (kỹ thuật xây dựng fitness function để đánh giá fitness score cho từng chromosome):
hãy hoàn thiện function compute_fitness(individual) để tính fitness values của một chromosome
bằng cách nghịch đảo giá trị của hàm loss theo công thức fitness = 1 / (loss + 1). Hàm com-
pute_fitness(individual) đánh giá độ tốt của một cá thể. Giá trị càng lớn thì cá thể càng tốt.

In [54]:
features_X, sales_Y = load_data_from_file()


def compute_loss(individual):
	theta = np.array(individual)
	y_hat = features_X.dot(theta)
	loss = np.multiply((y_hat - sales_Y), (y_hat - sales_Y)).mean()
	return loss


def compute_fitness(individual):
	loss = compute_loss(individual)
	fitness_value = 0
	# ************ your code here ************

	fitness_value = 1 / (loss + 1)

	return fitness_value

In [55]:
features_X, sales_Y = load_data_from_file()
individual = [4.09, 4.82, 3.10, 4.02]
fitness_score = compute_fitness(individual)
print(fitness_score)

1.0262143260061246e-06


Bài tập 4 (kỹ thuật thực hiện crossover giữa 2 chromosomes): hãy hoàn thiện function crossover(individual1,
individual2, crossover_rate = 0.9) để thực hiện crossover giữa 2 individual (chromosome). Bước
này, thực hiện việc lai tạo (trao đổi gen) giữa 2 individual với tỉ lệ crossover_rate

In [67]:
def crossover(individual1, individual2, crossover_rate = 0.9):
	individual1_new = individual1.copy()
	individual2_new = individual2.copy()
	#*************** Your code here **************
	for i in range(len(individual1_new)):
		if random.random() < crossover_rate:
			individual1_new[i], individual2_new[i] = individual2[i], individual1[i]

	# individual1_new = [x * crossover_rate for x in individual1_new]
	# individual2_new = [x * crossover_rate for x in individual2_new]

	return individual1_new, individual2_new

In [68]:
# question 5
individual1 = [4.09, 4.82, 3.10, 4.02]
individual2 = [3.44, 2.57, -0.79, -2.41]
individual1, individual2 = crossover(individual1, individual2, 2.0)
print(" individual1 : ", individual1)
print(" individual2 : ", individual2)

 individual1 :  [3.44, 2.57, -0.79, -2.41]
 individual2 :  [4.09, 4.82, 3.1, 4.02]


Bài tập 5 (kỹ thuật mutation với chromosome): hãy hoàn thiện function mutate(individual, muta-tion_rate = 0.05) để thực hiện việc đột biến cho một cá thể với tỉ lệ đột biến là mutation_rate.

In [69]:
def mutate(individual, mutation_rate = 0.05):
	individual_m = individual.copy()
	# ******** Your code here ******************
	for i in range(len(individual_m)):
		if random.random() < mutation_rate:
			individual_m[i] = random.uniform(-mutation_rate, mutation_rate)

	return individual_m

Question 6: Hãy cho biết kết quả của đoạn chương trình sau:

In [70]:
before_individual = [4.09, 4.82, 3.10, 4.02]
after_individual = mutate(individual, mutation_rate = 2.0)
print(before_individual == after_individual)


False


Bài tập 6 (khởi tạo population đầu tiên): hãy hoàn thiện function initializePopulation(m) để thực
hiện việc khởi tạo m cá thể (individual, chromosome) cho population.

In [ ]:
def initializePopulation(m):
	population = [create_individual() for _ in range(m)]
	return population


Bài tập 7 (Kỹ thuật selection để thực hiện việc chọc lọc tư nhiên, đào thải những cá thể yếu trong
population): hãy hoàn thiện function selection() để thực hiện việc chọn lọc tự nhiên cá thể tốt vào thế
hệ kế tiếp.



In [ ]:
def selection(sorted_old_population, m = 100):
	index1 = random.randint(0, m - 1)
	while True:
		index2 = random.randint(0, m - 1)
		if index2 != index1:
			break
	individual_s = sorted_old_population[index1]
	if index2 > index1:
		individual_s = sorted_old_population[index2]
	return individual_s

Bài tập 8 (Kỹ thuật tạo ra quần thể (population) mới: Hãy hoàn thiện function create_new_population()
để tạo ra quần thể mới đựa trên các bước selection, crossover và mutation. Lưu ý rằng chúng ta sẽ sử
dụng giải thuât Elitist algorithms để đảm bảo rằng elitism cá thể tốt nhất không bị loại bỏ, bằng cách
chuyển chúng trực tiếp sang thế hệ tiếp theo.

In [71]:
def create_new_population(old_population, elitism = 2, gen = 1):
	m = len(old_population)
	sorted_population = sorted(old_population, key = compute_fitness)
	if gen % 1 == 0:
		print(" Best loss :", compute_loss(sorted_population[m - 1]), " with chromsome : ",
		      sorted_population[m - 1])
	new_populations = []
	while len(new_populations) < m - elitism:
		# selection
		# **************** your code here ****************
		parent1 = selection(sorted_population, m)
		parent2 = selection(sorted_population, m)
		# crossover
		# **************** your code here ****************
		crossover(new_populations[0], new_populations[-1])
		# mutation
		# **************** your code here ****************
		new_populations.append(mutate(parent1, mutation_rate = 0.5))
		new_populations.append(mutate(parent1, mutation_rate = 0.5))
	# copy elitism chromosomes that have best fitness score to the next generation
	for ind in sorted_population[m - elitism:]:
		if ind not in new_populations:
			new_populations.append(ind)

	# **************** your code here ****************

	return new_populations, compute_loss(sorted_population[m - 1])

In [72]:
individual1 = [4.09, 4.82, 3.10, 4.02]
individual2 = [3.44, 2.57, -0.79, -2.41]
old_population = [individual1, individual2]
new_population, _ = create_new_population(old_population, elitism = 2, gen = 1)



 Best loss : 121540.42335680498  with chromsome :  [3.44, 2.57, -0.79, -2.41]


Bài tập 9 (All-in-one) Hãy hoàn thiện function run_GA() để tìm tham số θ1, θ2, θ3, θ4 tối ưu sử dụng
giải thuật di truyền.

In [76]:
def run_GA():
	n_generations = 100
	m = 600
	features_X, sales_Y = load_data_from_file()
	population = initializePopulation(m)
	losses_list = []
	for i in range(n_generations):
		# *********** your code here *************
		
		
		_, loss = create_new_population(population[i], elitism = 2, gen = 1)
		losses_list.append(loss)
	return losses_list

Bài tập 10 (Trực quan hoá loss values) Hoàn thiện function visualize_loss()để thể hiện giá trị loss
tốt nhất của cá thể (chromosome) ứng với từng thế hệ (generations) (hình 2)

In [74]:
import matplotlib.pyplot as plt


def visualize_loss(losses_list):
	# *********** your code here *************
	plt.plot(losses_list)
	
	

losses_list = run_GA()
visualize_loss(losses_list)

NameError: name 'initializePopulation' is not defined